# .github/workflows/fetch_news.yml
name: Fetch Daily News

on:
  schedule:
    # Draait elke dag om 7:00 UTC (is 8:00 of 9:00 in NL)
    - cron: '0 7 * * *'
  workflow_dispatch: # Maakt het mogelijk om handmatig te starten

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    # Geef de workflow schrijfrechten op de repository
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch news and save to _data folder
        run: |
          # Maak de _data map aan als deze niet bestaat
          mkdir -p _data
          # Roep de API aan en sla de 'results' op in de juiste map
          curl "https://newsdata.io/api/1/news?apikey=${{ secrets.NEWSDATA_API_KEY }}&q=Mark%20Eijbaard&language=nl" | jq '.results' > _data/news.json

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/news.json
          # Commit alleen als er wijzigingen zijn
          git diff --staged --quiet || git commit -m "Update daily news"
          git push
