# .github/workflows/fetch_news.yml
name: Fetch Daily News

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch and process news
        run: |
          set -e
          mkdir -p _data

          # Stap 1: Haal de stabiele JSON-feed op.
          curl -L -s "${{ secrets.RSS_FEED_URL }}" -o new_articles_raw.json

          # Stap 2: Herstructureer de JSON met de door jou gecorrigeerde veld-mapping.
          jq '[.items[] | {
              title: .title,
              link: .url,
              pubDate: (if .date_published then ((.date_published | split(".")[0]) + "Z" | fromdate | strftime("%Y-%m-%d %H:%M:%S")) else "" end),
              description: .content_text,
              source_id: .source, # <-- GECORRIGEERD
              image_url: .image,
              creator: [ (if .authors and .authors[0].name then .authors[0].name else "" end) ]
            } | select( (.title | test("Eijbaard"; "i")) or (.description | test("Eijbaard"; "i")) )]' new_articles_raw.json > new_articles.json

          # Stap 3: Voeg samen en ontdubbel op basis van de ARTIKELTITEL.
          if jq -e 'length > 0' new_articles.json > /dev/null; then
            echo "Nieuwe, relevante artikelen gevonden. Bezig met samenvoegen."
            
            if [ ! -f "_data/news.json" ]; then
              echo "[[]]" > _data/news.json
            fi
            
            # Stap 3a: Pak de bestaande artikelen uit.
            jq '.[0]' _data/news.json > old_articles.json
            
            # Stap 3b: Voeg samen, ontdubbel op TITEL en sorteer.
            jq -s '.[0] + .[1] | unique_by(.title) | sort_by(.pubDate) | reverse' old_articles.json new_articles.json > combined_articles.json # <-- GECORRIGEERD
            
            # Stap 3c: Pak de gecombineerde lijst weer in.
            jq '[.]' combined_articles.json > temp_news.json && mv temp_news.json _data/news.json

          else
            echo "Geen nieuwe artikelen gevonden die de naam 'Eijbaard' bevatten."
          fi
      
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/news.json
          git diff --staged --quiet || git commit -m "Update daily news"
          git push
