name: Fetch Daily News

on:
  schedule:
    - cron: '0 7 * * *'   # dagelijks om 07:00 UTC
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch and process news
        run: |
          set -euo pipefail
          mkdir -p _data

          echo "=== Stap 1: Download feed ==="
          curl -L -s "${{ secrets.RSS_FEED_URL }}" -o new_articles_raw.json

          echo "Feed bestandsgrootte:"
          wc -c new_articles_raw.json || true

          echo "Totaal aantal items in feed:"
          jq '(.items? // .entries? // .articles? // .data? // []) | length' new_articles_raw.json

          echo "=== Stap 2: Bouw new_articles.json ==="
          jq '[ (.items? // .entries? // .articles? // .data? // []) | .[]
              | {
                  title: (.title // ""),
                  link: (.url // .id // ""),
                  pubDate: (.date_published // ""),
                  description: (.content_text // .content_html // .summary // .description // ""),
                  source_id: ((.authors[0].name // "") | select(. != "") // (.link // "" | capture("https?://(?<domain>[^/]+)/") | .domain // "Onbekende bron")),
                  image_url: (.image // ""),
                  creator: [ (.authors[0].name // "") ]
                }
              | select([.title, .description] | map((. // "") | test("Eijbaard"; "i")) | any)
          ]' new_articles_raw.json > new_articles.json

          FILTERED_COUNT=$(jq 'length' new_articles.json)
          echo "Aantal artikelen die 'Eijbaard' bevatten: $FILTERED_COUNT"

          echo "=== Stap 3: Merge met bestaand archief ==="
          if [ "$FILTERED_COUNT" -gt 0 ]; then
            node .github/scripts/merge_news.js _data/news.json new_articles.json > temp_news.json
            mv temp_news.json _data/news.json
            echo "Samenvoegen gelukt."
          else
            echo "Geen nieuwe artikelen gevonden die de naam 'Eijbaard' bevatten."
          fi
      
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/news.json
          git diff --staged --quiet || git commit -m "Update daily news"
          git push
