# .github/workflows/fetch_news.yml
name: Fetch Daily News

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch, merge, and sort news
        run: |
          mkdir -p _data
          # Stap 1: Haal nieuwe artikelen op en sla ze tijdelijk op
          curl "https://newsdata.io/api/1/news?apikey=${{ secrets.NEWSDATA_API_KEY }}&q=Mark%20Eijbaard&language=nl" | jq '.results' > new_articles.json

          # Stap 2: Controleer of er al een nieuwsbestand bestaat
          if [ -f "_data/news.json" ]; then
            # Stap 3a: Voeg oud en nieuw samen, verwijder duplicaten (op basis van de link), en sorteer op datum (nieuwste eerst)
            jq -s '.[0] + .[1] | unique_by(.link) | sort_by(.pubDate) | reverse' _data/news.json new_articles.json > temp_news.json && mv temp_news.json _data/news.json
          else
            # Stap 3b: Als er geen oud bestand is, gebruik dan alleen de nieuwe artikelen, gesorteerd
            jq 'sort_by(.pubDate) | reverse' new_articles.json > _data/news.json
          fi
