name: Update news

on:
  schedule:
    - cron: "0 * * * *"   # elk uur
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download and process RSS feed
        run: bash .github/scripts/process_feed.sh

      - name: Merge news
        run: node .github/scripts/merge_news.js

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/news.json
          git diff --cached --quiet || git commit -m "Update news.json"
          git push
